---
title: '2021'
output: html_document
date: "2024-03-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library("tidyverse")
library("janitor")
library("naniar")
library("ggplot2")
library("shiny")
library(shinydashboard)
```

```{r}
happy <- read.csv("data/archive/2021.csv") %>% clean_names()
```

#box plot of happiness in each region  
```{r}
happy %>% 
  ggplot(aes(x=regional_indicator, y=ladder_score, fill="linen"))+
  geom_boxplot(alpha=0.4)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1))
```

#box plot of gdp in each region
```{r}
happy %>% 
  ggplot(aes(x=regional_indicator, y=logged_gdp_per_capita, fill="linen"))+
  geom_boxplot(alpha=0.4)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1))
```

#I am making an UI
```{r}
runApp("plot_iris.R")
```

#scatter plot of all comparable variable.  
```{r}
names(happy)
```

```{r}
library(shiny)

ui <- fluidPage(
  selectInput("x", "Select X Variable", choices = c("regional_indicator", "ladder_score", "logged_gdp_per_capita", "social_support", "healthy_life_expectancy", "freedom_to_make_life_choices"), selected = "ladder_score"),
  
  selectInput("y", "Select Y Variable", choices = c("regional_indicator", "ladder_score", "logged_gdp_per_capita", "social_support", "healthy_life_expectancy", "freedom_to_make_life_choices"), selected = "ladder_score"),
  
  plotOutput("plot")
)

server <- function(input, output) {
  output$plot <- renderPlot({
    
    ggplot(data=happy, aes_string(x=input$x, y=input$y, color="country_name"))+
      geom_point()+
      theme(axis.text.x = element_text(angle = 30, hjust = 1))+
      geom_smooth(method=lm, se=F, na.rm = T)+
      theme_light(base_size=18)
  
})
}

shinyApp(ui, server)
```

#each variable selected by country
```{r}
library(shiny)

ui <- fluidPage(
  
  radioButtons("x", "Select Fill Variable", choices=c("regional_indicator", "ladder_score", "logged_gdp_per_capita", "social_support", "healthy_life_expectancy", "freedom_to_make_life_choices"),
               selected="regional_indicator"),
  
  plotOutput("plot")
)

server <- function(input, output, session) {
  output$plot <- renderPlot({
    
    ggplot(data=happy, aes_string(x="country_name", fill=input$x))+
      geom_bar(alpha=0.8, color="black")+
      labs(x=NULL, y=NULL, fill="Country")
})
}

shinyApp(ui, server)
```

```{r}
happy %>% 
  
  ggplot(aes(x=regional_indicator, y=ladder_score))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```









